### PR TITLE
add new custom fields, passing tests, and update to reflect outbound int

### PR DESCRIPTION
**Pull request by ros3bud**
Solves issues: #3 #4 and #5

### CODE REVIEW

**Comment by alexkwolfe** [comment]
I'm sorry I missed this whole conversation. But are agent ID and notes really standard LeadPerfection fields, or are they custom fields that a user has added to their LeadPerfection account?

**Comment by ros3bud** [comment]
The fields were added to the LeadPerfection DB. So we thought that made them standard fields. Is that correct?

**Comment by alexkwolfe** [comment]
Depends on how they were added. If they were added in the context of just one LeadPerfection account, that's different than being added to the DB for all accounts. It would mean the difference between them being standard LeadPerfection fields and custom fields for one LeadPerfection account. If the latter is the case, then we don't want to add them to the integration as has been done here.

**Comment by ros3bud** [comment]
I see, ok. I will need to get some more information in order to figure out what context these fields were added in. Mind if we circle back about this on Monday?

**Comment by zalary** [comment]
From LeadPerfection

    It looks like you guys just use the LeadFormExtraFields.asp post. I added two new fields to it:

    AgentID – variable character field. Accepts up to 25 characters 
    Notes – variable character field. Set as a MAX since I was not sure if you were putting any limits on the form yourself.

    Obviously these fields are not visible on the site yet but you can begin to post data to them. If you want to do some tests I can look in the database to make sure they are coming through OK.

That reads to me like those fields will available to anyone using that LeadFormExtraFields endpoint.

**Comment by alexkwolfe** [comment]
Is it worth confirming that?

**Comment by ros3bud** [comment]
In the process of confirming.

**Comment by cgrayson** [comment]
The latest from #3: "These were custom fields added for First Street. They will not be useful to other users of the integration."

Discussed with Alex; we have an idea for a general-purpose scheme for this kind of situation. I thought I'd go ahead and make those changes in lieu of this PR, if you don't mind. :grinning:

**Comment by cgrayson** [comment]
@ros3bud do you need this to be open still?

**Pull request closed without merging**
